
/*Generated by the CoffeeCup Web Editor - www.coffeecup.com
			

Description...
			
			
@created:           11/02/2015 - 10:20:29
@today:             11/02/2015
@project:           No Project
@path:              /Users/preety/Documents/QuickFile1.txt
			
@author:            Your name
@company:           Your company
@Copyright:         A copyright notice
			
@version:           $Revision:$ */



function checkFields() {
  if (document.getElementById("fullName").value.length === 0) {
	  alert("Please enter your name.");
	  return false;
  }


  if (document.getElementById("country").selectedIndex === 0) {
	  alert("Please select a country.");
	  return false;
  }
  
  if (document.getElementById("employerName").value.length === 0) {
	  alert("Please enter your employer's name.");
	  return false;
  }
  
  if (document.getElementById("jobTitle").value.length === 0) {
	  alert("Please enter your job title.");
	  return false;
  }
  
  if (document.getElementById("fullAddress").value.length === 0) {
	  alert ("Please enter your address.");
	  return false;
  }
  
  if (document.getElementById("DOBMonth").selectedIndex === 0) {
	  alert("Please enter your birth month.");
	  return false;
  }
	  
  if  (document.getElementById("DOBDay").selectedIndex === 0) {
	  alert("Please enter your birth day.");
	  return false;
  }
  
  if (document.getElementById("DOBYear").selectedIndex === 0) {
	  alert("Please enter your birth year.");
	  return false;
  }
  
  var userMonth = document.getElementById("DOBMonth").selectedIndex - 1;
  var userDayIndex = document.getElementById("DOBDay").selectedIndex;
  var userDay = document.getElementById("DOBDay")[userDayIndex].value;
  var userYearIndex = document.getElementById("DOBYear").selectedIndex;
  var userYear = document.getElementById("DOBYear")[userYearIndex].value;
  var d = new Date();
  var yearNow = d.getFullYear();
  var latestYear = yearNow - 18; 
  var todayDay = d.getDate();
  var todayMonth = d.getMonth();
  var latestBirthday = new Date(latestYear, todayMonth, todayDay);
  var userBirthday = new Date(userYear, userMonth, userDay);
  if (userBirthday > latestBirthday) {
	  alert("Sorry, you must be over 18 to complete an entry.");
	  return false;
  }

  if (document.getElementById("placeOfBirth").value.length === 0) {
	  alert("Please enter your place of birth.");
	  return false;
  }
  
  if (document.getElementById("passportNumber").value.length === 0) {
	  alert("Please enter your Passport ID.");
	  return false;
  }
  
  if (document.getElementById("emailAddress").value.length === 0) {
	  alert("Please enter your email address.");
	  return false;
  }
  
	  var emailValue = document.getElementById("emailAddress").value;
	  var atpos = emailValue.indexOf("@");
	  var dotpos = emailValue.lastIndexOf(".");
	
	  if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 > emailValue.length) {
		  alert("Please enter a valid email address.");
		  return false;
	  }
  
  if (document.getElementById("tel").value.length === 0) {
	  alert("1Please enter your 10 digit telephone number. (Numeric characters only please!)");
	  return false;
  } 
  
  if (isNaN(document.getElementById("tel").value)) {
	  alert("2Please enter your 10 digit telephone number. (Numeric characters only please!)");
	  return false;
  }
  
  if (document.getElementById("tel").value.length < 10) {
	  alert("3Please enter your 10 digit telephone number. (Numeric characters only please!)");
	  return false;
  }
}
