<?php
			
/* Generated by the CoffeeCup Web Editor - www.coffeecup.com */
			
/*
Description...
			
			
			
			
@created:           09/02/2015 - 14:22:34
@today:             09/02/2015
@project:           No Project
@path:              /Applications/XAMPP/xamppfiles/htdocs/Neel/mySQLconnect.php
			
@author:            Neel Sinha
@company:           Deque Systems
@Copyright:         @Deque Systems

@version:           $Revision:$ 1.0
@description: db connection*/
	
$dbgb = new mysqli("localhost", "root", "", "itarGuestBook");
if ($dbgb->connect_errno)
{
	die("Failed to connect to DB " . $dbgb->connect_errno);
}
?>
